# Generated by Django 5.0.2 on 2024-02-19 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='title',
        ),
    ]
