# Generated by Django 5.0.2 on 2024-02-19 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_name_test_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
