# Generated by Django 5.0.2 on 2024-03-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rest_password_token',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
