# Generated by Django 5.0.2 on 2024-03-03 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_rest_password_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='rest_password_expire',
            new_name='reset_password_expire',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='rest_password_token',
            new_name='reset_password_token',
        ),
    ]
